telegram:
  bot:
    mode: webhook
    webhook:
      auto-register: false
      auto-remove: false
    token: "your-token-is-here"

server:
  port: 8181

spring:
  application:
    name: telegram-bot-sample-webhook
