spring:
  application:
    name: telegram-bot-advanced-sample-long-polling

telegram:
  bot:
    token: "your-bot-token-here"

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
